### PR TITLE
Add extended color palette to colors page.

### PR DESCRIPTION
**Pull request by valariems**
@dannychapman When you're ready to review, let's talk about how we want to name colors.

### CODE REVIEW

**Comment by valariems** [comment]
@dannychapman 

screen shot 2019-02-20 at 10 16 41 am

**Comment by dannychapman** [comment]
@paulsmith See above!

**Comment by paulsmith** [comment]
So so exciting

**Comment by goldenmeanie** [comment]
I came across this in conversation. This is great! Do you have plans to make style tiles or some other guidance on how these secondary colors should be used?

**Pull request merged**
